# Generated by Django 5.1.4 on 2024-12-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0004_readinglist_readinglistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readinglistitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='readinglistitem',
            name='book',
            field=models.CharField(max_length=255),
        ),
    ]
