# Generated by Django 5.1.4 on 2024-12-29 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0005_alter_readinglistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglistitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.book'),
        ),
    ]
